---
title: "project"
author: "Ram-G02494015"
date: "2022-11-04"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(forecast)
library(dplyr)
library(TSstudio)
library(ggplot2)
library(ggfortify)
```

```{r}
#loading data
electricity_df<-read.csv(file="Electricity_Sales_to_Ultimate_Customers_Total_Monthly.csv")
head(electricity_df)
```

```{r "Seperating Columns"}
electricity_new<-separate(electricity_df, col=Month, into=c('Month', 'Year'), sep='-')
head(electricity_new)
```

```{r "Editing Year"}
electricity_new$Year <-as.numeric(electricity_new$Year)
electricity_new<-electricity_new %>% 
mutate(electricity_new, YEAR = ifelse(Year %in% 0:9,paste(200, Year, sep=""),
                                      ifelse(Year %in% 10:22,paste(20, Year, sep=""),
                                     ifelse(Year %in% 73:99, paste(19, Year, sep=""),""))))
head(electricity_new)
```
```{r}
electricity_new<-electricity_new %>% 
mutate(electricity_new, MONTH = match(Month, month.abb))

electricity_new<-electricity_new %>% 
mutate(electricity_new, MONTH = ifelse(MONTH %in% 0:9,paste(0, MONTH, sep=""),MONTH))



head(electricity_new)

```

```{r "Sorting by month and year"}
electricity_new<-electricity_new[
  with(electricity_new, order(electricity_new$YEAR, electricity_new$MONTH)),
]
head(electricity_new)

```

```{r "as date"}

DATE <- c(paste(electricity_new$YEAR,"-",electricity_new$MONTH, sep = ""))
CONSUMPTION <- c(electricity_new$Series.ID..TOTAL.ESTCPUS.M.Million.Kilowatthours)
electricity_final <- data.frame(DATE,CONSUMPTION)
head(electricity_final)

exploratory<-data.frame(YEAR=electricity_new$YEAR,MONTH=electricity_new$MONTH, CONSUMPTION)

write.csv(electricity_final,"electricity_final.csv")
write.csv(exploratory,"exploratory.csv")
```
```{r "Converting to time series"}
dataTS <- ts(electricity_final$CONSUMPTION, start=1973, frequency=12)
head(dataTS)
autoplot(dataTS)
```